#!/bin/bash

set -e

if [[ "$(which brew)" ]]; then
  INSTALLER_CMD="brew install"
elif [[ "$(which apt)" ]]; then
  INSTALLER_CMD="apt install"
else
  echo "Could not find brew or apt."
  exit 1
fi

set -x

pip install flake8
pip install vim-vint
$INSTALLER_CMD shellcheck
