#!/usr/bin/env bash

set -e
source _scripts/_helpers.sh

if [[ -n "$(which apt-get)" ]]; then
  if _confirm "Run linux install scripts?"; then
    _scripts/install-linux || _error "linux install failed"
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  if _confirm "Run MacOS install scripts?"; then
    _scripts/install-macos || _error "macos install failed"
  fi
fi

if _confirm "Install stow packages?"; then
  _scripts/install-stow-packages || _error "stow packages failed"
fi

if _confirm "Install autojump?"; then
  _scripts/install-autojump || _error "autojump install failed"
fi

if _confirm "Install dotfiles dev dependencies?"; then
  _scripts/install-dev || _error "Dotfiles dev deps install failed"
fi
