#!/bin/bash

set -e
DOTFILES_DIR="$(dirname $0)"
source "$DOTFILES_DIR/_scripts/_helpers.sh"

INSTALLED_INDEX_TMP="$(mktemp)"
INSTALLED_INDEX="$DOTFILES_DIR/.installed_packages"

stowable="$(ls -d */ | grep -v _ | grep -v stow | tr -d /)"

cd "$DOTFILES_DIR"

install_package() {
  local package=$1
  (
  cd "$package"
  examples="$( (ls -a | grep example) || echo)"
  for example in $examples; do
    cp -vn "$example" "$(echo $example | sed 's/.example//')"
  done
  )
  [[ -e "$package/_install" ]] && $package/_install
  stow $package
}

_info "Creating directories"
mkdir -vp $HOME/.config
mkdir -vp $HOME/bin
mkdir -vp $HOME/lib
mkdir -vp $HOME/.gnupg

_info "Initializing stow"
cp ./stow/.stowrc.example ./stow/.stowrc
sed -i "s|\$HOME|$HOME|" ./stow/.stowrc
cat ./stow/.stowrc
echo "stow" >> "$INSTALLED_INDEX_TMP"
stow --target $HOME --ignore=.*.example stow

for package in $stowable; do
  if _confirm "Install $package?"; then
    _info "Installing $package"
    echo "$package" >> "$INSTALLED_INDEX_TMP"
    install_package $package
  fi
done

mv -f "$INSTALLED_INDEX_TMP" "$INSTALLED_INDEX"

_info "Installed these packages:"
cat "$INSTALLED_INDEX"

_info "Completed dotfile packages install"
