#!/bin/bash

set -e

if [[ $(which dotfilesdir) ]]; then
  DOTFILES_DIR=$(dotfilesdir)
else
  DOTFILES_DIR=.
fi

# fork so current directory does change when calling via zsh/bin/restow
(
  cd $DOTFILES_DIR
  # setup stow first
  stow --target=$HOME --restow --verbose stow
  # then stow everything else
  ls -d */ | grep -v _ | grep -v stow | xargs -I {} stow {}
)
