#!/bin/bash
set -e
source "$(dirname $0)/_scripts/_helpers.sh"

cd "$(dirname $0)"

_header "Uninstalling stow packages"
stowable="$(ls -d */ | grep -v _ | grep -v stow | tr -d /)"

echo "$stowable" |
while read package; do
  _info "Uninstalling $package"
  stow --target $HOME --delete $package
done

_info "Uninstalling stow"
stow --target $HOME --delete stow

rm -vf ./.installed_packages

_info "Done"
