#!/usr/bin/env bash

set -e
source "$(dirname $0)/_scripts/_helpers.sh"

INSTALLED_INDEX=./.installed_packages
_info "Updating stow packages"

if [[ ! -f "$INSTALLED_INDEX" ]]; then
  _error "No packages have been installed. Did you run ./install?"
  exit 1
fi

HAS_ERROR=""
while read package; do
  echo -n "==> Restowing package $package..."
  if stow --target=$HOME --restow --verbose=0 $package >/dev/null 2>&1; then
    echo -n " done"
  else
    HAS_ERROR=1
    echo -en " ${__red}error$__color_off"
  fi
  echo
done < $INSTALLED_INDEX

if [[ $HAS_ERROR ]] ; then
  echo
  _error "One or more packages could not be stowed. Manually run stow and fix."
  exit 1
fi
