#!/usr/bin/env bash
set -ex

cd "$(dirname $0)"

[[ -z "$(which brew)" ]] && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew tap homebrew/bundle
brew bundle -v
