#!/usr/bin/env bash

set -e
SCRIPTS_DIR="$(dirname $0)"

FAILED=()
attempt_script() {
  _info "$1"
  if ! $SCRIPTS_DIR/$1; then
    _error "$1 failed"
    FAILED+=($1)
  fi
}

source $SCRIPTS_DIR/_helpers.sh

if is_executable apt-get; then
  if _confirm "Run linux install scripts?"; then
    attempt_script "install-linux"
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  if _confirm "Run MacOS install scripts?"; then
    attempt_script "install-macos"
  fi
fi

if ! is_executable autojump; then
  attempt_script "install-autojump"
fi

if [[ ! -d $HOME/.zplug ]]; then
  attempt_script "install-zplug"
fi

if [[ ! -d $HOME/.fzf ]]; then
  attempt_script "install-fzf"
fi

if _confirm "Install dotfiles dev dependencies?"; then
  attempt_script "install-dev"
fi

if [[ "$(hostname)" == "finn" ]]; then
  attempt_script "install-pgp-key"
fi

mkdir -p $HOME/repos

echo "==> Bootstrapping finished"

if [[ -n "$FAILED" ]]; then
  _error "The following install scripts failed to complete:"
  for fail in ${FAILED[*]}; do
    _error "- $fail"
  done
fi
