#!/usr/bin/env bash
set -e
LOCALE=en_US
ENCODING=UTF-8

if ! grep "^$LOCALE.$ENCODING" /etc/locale.gen; then
  echo "==> Generating missing locale"
  echo "$LOCALE.$ENCODING $ENCODING" >> /etc/locale.gen
  locale-gen
fi

ENV_FILE=/etc/environment
if ! grep "LC_ALL" $ENV_FILE; then
  echo "==> Fixing $ENV_FILE"
  echo "LC_ALL=$LOCALE.$ENCODING
  LANG=$LOCALE.$ENCODING" > $ENV_FILE
fi

echo "Locale fixed. Logout and login for fix to take effect."
