#!/bin/bash

set -e

exe() { echo "==> $@"; $@; }

if [[ "$(which brew)" ]]; then
  INSTALLER_CMD="brew install"
elif [[ "$(which apt)" ]]; then
  INSTALLER_CMD="apt install"
else
  echo "Error: Could not find brew or apt."
  exit 1
fi

exe "pip install flake8 yapf vim-vint"
exe "$INSTALLER_CMD shellcheck"
