#!/usr/bin/env bash
set -e
source "$(dirname $0)/_helpers.sh"

_info "Installing termux deps"

pkg update
pkg upgrade
pkg install -y \
  bash \
  coreutils \
  curl \
  fzf \
  git \
  man \
  net-tools \
  openssh \
  proot \
  python \
  screen \
  stow \
  termux-tools \
  tracepath \
  tracepath \
  tree \
  util-linux \
  vim
