#!/usr/bin/env bash
set -e

exe() { echo "==> $@"; $@; }

exe "apt-get update"
exe "apt-get upgrade -y"
exe "apt-get install -y \
  git \
  mosh \
  psmisc \
  python \
  python-pip \
  screen \
  stow \
  tmux \
  tree \
  vim \
  zsh"
exe "apt-get clean"
