#!/usr/bin/env bash
set -e
source "$(dirname $0)/_helpers.sh"

cd "$(dirname $0)/../_macos"

if [[ -z "$(which brew)" ]]; then
  _header "Installing homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

_header "Brew bundling"
brew tap homebrew/bundle
brew bundle -v
