#!/usr/bin/env bash
set -e
source "$(dirname $0)/_helpers.sh"

_info "Installing linux deps"

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y \
  stow \
  screen \
  vim \
  psmisc
