#!/usr/bin/env bash
set -e
source "$(dirname $0)/_helpers.sh"

_info "Installing linux deps"

apt-get update
apt-get upgrade -y
apt-get install -y \
  mosh \
  psmisc \
  python \
  screen \
  stow \
  tree \
  vim
