#!/usr/bin/env bash
set -ex

if [[ -n "$SUDO_USER" ]]; then
  export USER="$SUDO_USER"
  export HOME="/home/$SUDO_USER"
fi

mkdir -p $HOME/.nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
