#!/usr/bin/env bash
# Install my PGP key from keybase.
set -e
source "$(dirname $0)/_helpers.sh"

KEYID="119BA45BFDF0E612"

_info "Installing PGP key with id $KEYID"
if ! is_executable keybase; then
  _error "Keybase not installed."
  exit 1
fi

_info "Installing public key"
keybase pgp export --query $KEYID | gpg --import

_info "Installing private key"
keybase pgp export --query $KEYID --secret |
  gpg --allow-secret-key-import --import
