#!/bin/bash

set -e
DOTFILES_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "$(dirname "$0")/_helpers.sh"

INSTALLED_INDEX_TMP="$(mktemp)"
INSTALLED_INDEX="$DOTFILES_DIR/.installed_packages"

stowable="$(find . -maxdepth 1 -type d ! -name '_*' ! -name 'stow' ! -name '.' | sed 's|^\./||')"

cd "$DOTFILES_DIR"

install_package() {
  local package=$1
  (
  cd "$package"
  for example in ./*.example; do
    [[ -e "$example" ]] || continue
    cp -vn "$example" "${example%.example}"
  done
  )
  [[ -e "$package/_install" ]] && "$package/_install"
  stow --target="$HOME" --restow --verbose "$package"
}

_info "Creating directories"
mkdir -vp "$HOME/.config"
mkdir -vp "$HOME/.local/bin"
mkdir -vp "$HOME/.local/lib"
mkdir -vp "$HOME/.local/share"
mkdir -vp "$HOME/.local/etc"
mkdir -vp "$HOME/.gnupg"

_info "Initializing stow"
echo "stow" >> "$INSTALLED_INDEX_TMP"
stow --target="$HOME" --restow --verbose stow

_info "Installing npm packages"
npm install random-words

for package in $stowable; do
  if _confirm "Install $package?"; then
    _info "Installing $package"
    echo "$package" >> "$INSTALLED_INDEX_TMP"
    install_package "$package"
  fi
done

mv -f "$INSTALLED_INDEX_TMP" "$INSTALLED_INDEX"

_info "Installed these packages:"
cat "$INSTALLED_INDEX"

_info "Completed dotfile packages install"
