#!/bin/bash

set -e
source "$(dirname $0)/_helpers.sh"

DOTFILES_DIR="$(dirname $0)/.."
INSTALLED_INDEX_TMP="$(mktemp)"
INSTALLED_INDEX="$DOTFILES_DIR/.installed_packages"

stowable="$(ls -d */ | grep -v _ | grep -v stow | tr -d /)"

cd "$DOTFILES_DIR"

_info "Installing dotfile packages"

_info "Initializing .stowrc"
cp -vi ./stow/.stowrc.example ./stow/.stowrc
sed -i "s|\$HOME|$HOME|" ./stow/.stowrc
cat ./stow/.stowrc
echo "stow" >> "$INSTALLED_INDEX_TMP"

_info "Installing stow"
stow --target $HOME --ignore=.*.example stow

for package in $stowable; do
  if _confirm "Install $package?"; then
    _info "Installing $package"
    echo "$package" >> "$INSTALLED_INDEX_TMP"
    (
    cd $package
    examples="$((ls -a | grep example) || echo)"
    for example in $examples; do
      cp -vn "$example" "$(echo $example | sed 's/.example//')"
    done
    )
    stow $package
  fi
done

mv -f "$INSTALLED_INDEX_TMP" "$INSTALLED_INDEX"

_info "Installed these packages:"
cat "$INSTALLED_INDEX"

_info "Completed dotfile packages install"
