#!/usr/bin/env bash
set -e

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "Error: OS $OSTYPE not compatible with script"
  exit 1
fi

if [[ -n "$SUDO_USER" ]]; then
  export USER="$SUDO_USER"
  export HOME="/home/$SUDO_USER"
fi

files="$(ls -A "$HOME" | xargs readlink -f)"
GROUP=$(id -gn "$USER")
owner="$USER:$GROUP"

echo "Files to update:"
echo -e "$files"

echo -n "==> Updating ownership to '$owner'. Continue? [y/n] "
read -r -n 1 ans
echo

if [[ "$ans" != "y" ]]; then
  exit 0
fi

echo -e "$files" | xargs chown -v "$owner"
