#!/usr/bin/env bash
set -ex

cd "$(mktemp -d)"

git clone --depth=1 https://github.com/StevenBlack/hosts .

pip3 install --user -r requirements.txt

python3 testUpdateHostsFile.py

cat << EOF > whitelist
hulu.com
thepiratebay.org
EOF

cat << EOF > myhosts
127.0.0.1 finn.local
EOF

python3 updateHostsFile.py --auto --replace --backup --flush-dns-cache
