#!/usr/bin/env bash
# Install keybase cli for Ubuntu, Debian, etc env.
# For macOS use `brew cask install keybase`.
# For others see https://keybase.io/docs/the_app/install_linux
set -e
source "$(dirname $0)/_helpers.sh"

if ! is_executable apt-get; then
  _error "$0 not compatible with this environment."
  exit 1
fi

if is_executable keybase; then
  _info "Keybase already installed"
  exit 0
fi

if ! is_executable gpg; then
  _info "Installing gpg"
  sudo apt-get update
  sudo apt-get install -y gnupg2
fi

_info "Downloading keybase package"
TEMP_DIR="$(mktemp -d)"
case "$(lscpu | grep 'Architecture')" in
  *64*)
    curl https://prerelease.keybase.io/keybase_amd64.deb -o $TEMP_DIR/keybase.deb
    ;;
  *32*)
    curl https://prerelease.keybase.io/keybase_i386.deb -o $TEMP_DIR/keybase.deb
    ;;
  *)
    _error "Could not detect architecture."
    exit 1
    ;;
esac

_info "Installing keybase"
sudo dpkg -i $TEMP_DIR/keybase.deb
sudo apt-get install -f
run_keybase
