#!/usr/bin/env ruby
require 'yaml'
require 'date'

notes = YAML.load_file("#{Dir.home}/.pnote/pnote.yml")

puts notes.count

notes.sort! { |a, b| DateTime.parse(a['created_at']) <=> DateTime.parse(b['created_at']) }

notes = notes.map.with_index do |note, index|
  note['uuid'] = note['id']
  note['id'] = index
  note
end

File.write("#{Dir.home}/.pnote/pnote_migrate_ids.yml", notes.to_yaml)

puts notes.sort_by{ |n| n['id'] }.reverse.first
