#!/bin/bash

book=$1

[[ -z $book ]] && exit 1

ids="$(dnote v $book | tail -n +2 | sed -r 's/.*\(([0-9]+)\).*/\1/g')"

for id in $ids; do
  content="$(dnote v $book $id | sed -e '/^[ \n-]/d')"
  pnote a $book "$content"
done
