#!/bin/bash

# Prevent multiple instances
if [ -f /tmp/auto-on-off.lock ]; then
  echo "Already running"
  exit 0
fi

touch /tmp/auto-on-off.lock

echo "Starting"

trap 'echo "Stopping" && rm /tmp/auto-on-off.lock' EXIT

exec log stream --predicate 'process == "UVCAssistant" && (eventMessage CONTAINS "start stream" || eventMessage CONTAINS "Stop Stream")' |
  /usr/bin/grep -vE --line-buffered '^Filter' | # filter out the informational output at launch
  tee /dev/stderr |                             # output matching events for debugging
  /usr/bin/sed -Eu 's/.*(start|stop).*/\1/' |   # reduce the log message down to a single word identifying the event/state
  while read -r event; do                       # store that word in the $event variable
    echo "Camera $event"
    if [ "$event" = "start" ]; then
      echo "Lamp on"
      /Users/piet/.local/lib/hid-litra/hid-litra.py -b 100
    else
      echo "Lamp off"
      /Users/piet/.local/lib/hid-litra/hid-litra.py off
    fi
  done
