#!/usr/bin/env bash
set -e


CMD=$1
shift

exe() { echo "==> $@" ; ($@) ; }

case $CMD in
  services-start)
    exe "brew services run --all"
    ;;


  blokkendoos-update)
    exe "yarn install"
    exe "yarn build:dev"
    ;;


  start)
    if [[ -z "$(docker ps | grep wk_app_YC_gateway)" ]]; then
      exe "yarn gateway"
    fi
    exe "yarn start:dev"
    ;;

  validate)
    exe "yarn build:all"
    exe "npx lerna run test:ci --stream"
  ;;

  e2e)
    (
      cd tf-aura-ui
      exe "yarn cypress:run:local"
    )
    (
      cd tf-aura-edge
      exe "yarn test:ci"
    )
  ;;

  *)
    if [[ -z "$CMD" ]]; then
      echo "USAGE: YC (update|start)"
      exit 0
    fi
    ;;
esac

cleanup
